export default {
  "common": {
    " ": " ",
    "yes": "Yes",
    "no": "No",
    "confirm": "Confirm",
    "assign": "Assign",
    "delete": "Delete",
    "ok": "OK",
    "close": "Close",
    "filter": "Filter",
    "product": "Product",
    "store": "Store",
    "loading": "Loading...",
    "setting": "Settings",
    "back": "Back",
    "dashboard": "Dashboard",
    "zones": "Zones",
    "stores": "Stores",
    "couriers": "Couriers",
    "tasks": "Tasks",
    "orders": "Orders",
    "notification": "Notifications",
    "warning": "Warning",
    "submit": "Submit",
    "cancel": "Cancel",
    "comment": "Comment",
    "tel": "Tel",
    "phone_number": "Phone",
    "not_set": "Not set",
    "name": "Name",
    "email": "Email",
    "customer": "Customer",
    "admin": "Admin",
    "current": "Current",
    "newest": "Newest",
    "Skipped": "Skipped",
    "clear_all": "Clear All",
    "all": "All",
    "save": "Save",
    "disabled": "Disabled",
    "margin": "Margin",
    "top": "Top",
    "bottom": "Bottom",
    "left": "Left",
    "right": "Right",
    "general": "General",
    "general_settings": "General Settings",
    "first_name": "First Name",
    "last_name": "Last Name",
    "status": "Status",
    "new": "New",
    "reload": "Reload",
    "selected": "Selected",
    "items": "Items",
    "clear_fliter": "Clear Filter",
    "search": "Search",
    "enter_password": "Enter password",
    "unlock": "Unlock",
    "qty": "Qty",
    "gift_cards": "Gift cards",
    "view_all": "View all",
    "profile": "Profile",
    "nick_name": "Nick name",
    "verification_code": "Verification code",
    "get_verification_code": "Get verification code",
    "edit": "Edit",
    "action": "Action",
    "send": "Send",
    "receiver": "Receiver",
    "email_phone": "Email/Phone",
    "change": "Change",
    "description": "Description",
    "remove": "Remove",
    "apply": "Apply",
    'complete_oreder': "Complete order",
    "category": "Category",
    "expired": "Expired",
    "optional": "Optional",
    "about": "About",
    "highlights": "Highlights",
    "customer_reviews": "Customer Reviews",
    "relevant_reviews": "Relevant Reviews",
    "ratings": "Ratings",
    "reviews": "Reviews",
    "buy": "Buy",
    "quantity": "Quantity",
    "out_of_stock": "Out of stock",
    "first": "First",
    "second": "Second",
    "previous": "PREVIOUS",
    "next": "NEXT",
    "get_started": "GET STARTED",
    "token": "Token",
    "home": "Home",
    "add": "Add",
    "are_you_sure": "Are you sure?",
    "feerules": "Fee Rules",
    "false": "False",
    "true": "True",
    "no_new_noti": "No new notifications",
    "ready": "Ready",
    "not_available": "Not available",
    "role": "Role",
    "customers": "Customers",
    "staffs": "Staffs",
    "contact_name": "Contact Name",
    "availabitlies": "Availabitlies",
    "subscribed_couriers": "Subscribed Couriers",
    "search_stores_with": "Search Store With...",
    "fee_rules": "Fee Rules",
    "sort_by": "Sort By",
    "documents": "Documents",
    "business_number": "Business Number",
    "value_added_tax_account_number": "Value Added Tax Account Number",
    "vat": "Value Added Tax Account Number",
    "business_start_dt": "Business Start Date",
    "special_instruction": "Special Instruction",
    "shared_customer": "Share Customer",
    "share_address_book": "Share Address Book",
    "third_party_access": "Third Party Access",
    "allow_third_party_access": "Allow Third Party Access",
    "contact_first_name": "Contact First Name",
    "contact_last_name": "Contact Last Name",
    "label": "Label",
    "business_building_name": "Business Building Name",
    "customer(optional)": "Customer(Opt)",
    "search_customers_with": "Search Customer With...",
    "customer_name/phone": "Customer Name/Phone",
    "ongoing": "Ongoing",
    "business_name": "Business Name",
    "auto_save": "Auto Save",
    "add_an_item": "Add an Item",
    "add_an_option": "Add an Option",
    "delivered_items": "Deliver Items",
    "staff": "Staff",
  },
  "common_column_titles": {
    "name": "Name",
    "contact": "Contact",
    "phone": "Phone",
    "action": "Action",
    "store_name": "Store Name",
    "address": "Address",
    "fee_rule": "Fee Rule",
    "order_id": "Order ID",
    "store": "Store",
    "pickup_range": "Pickup Range",
    "delivery_range": "Delivery Range",
    "from": "From",
    "to": "To",
    "status": "Status",
    "confirmed": "Confirmed",
    "info": "Info",
    "working_state": "Working State",
    "active_zones": "Active Zones",
    "subscribed_zones": "Subscribed Zones",
    "hours/week": "Hours/Week",
    "names": "Names",
    "time_limit": "Time Limit",
    "dollar_min": "dollar/min",
    "dollar/km_store": "dollar/km (Store)",
    "dollar/km_customer": "dollar/km (Customer)",
    "can_override": "Allow user modify delivery fee",
    "contact_info": "Contact Info",
    "office_info": "Office Info",
    "zone_name": "Zone Name",
    "base_distance": "Flat Fee Distance",
    "base_fee": "Flat Fee",
    "active_stores": "Aproved Stores",
    "pending_stores": "Pending Stores",
    "pendingStores": "Pending Stores",
    "pending_store": "Pending Store",
    "pending_store(other)": "Pending Store(Other)",
    "website": "Website",
    "business_type": "Business Type",
    "number_of_locations": "Number of Locations",
    "report": "Report",
    "last_seen": "Last Seen",
    "working_state_desc": "Courier's attendance status for the work place.",
    "active_zones_desc": "Courier's current working zones.",
    "subscribed_zones_desc": "Courier's subscribed working zones.",
    "collection_fee_per_min_desc": "Extra dollar amount per min paid to courier waiting beyond the collection time limit.",
    "base_distance_desc": "Flat delivery fee the business pays to the courier when delivery is within the base distance.",
    "per_km_fee_to_store_desc": "The per kilometer transit payment",
    "per_km_fee_to_customer_desc": "Extra dollar amount per km beyond the base fee paid to the courier.",
    "collection_time_limit_desc": "Beyond this limit, the business need to pay a courier extra dollar per min for waiting.",
    "base_fee_desc": "Basic fee charged when delivering from store to customers.",
    "can_override_desc": "If it set to Yes, it means the delivery fee defined in the task can be modifyied by user; with it set to NO means store can not modify the delivery fee for each delivery task.",
    "share_address_book_tooltip": "Allow Organization to access store customer address book",
    "allow_third_party_access_tooltip": "Allow Third Party (API Key) access and edit store information",
    "generate_next_order_id": "Generate next order Id",
    "delivery_fee_descript": "Delivery Fee is calcated based on store fee rule if it is not set",
    "calulate_estimated_delivery_Fee": "Calculate Esistmated Delivery Fee",
    "store_was_not_entered_or_not_recognized": "Please enter location from info",
    "fee_rule_was_not_assigned_to_the_selected_store_or_fee_rule_not_recognized": "Fee rule is not assigned to the selected store or fee rule is not recognized",
    "please_enter_destination_info": "Please enter destination info"
  },
  "common_setting": {
    "task_display": "Task Display",
    "auto_assign": "Auto Assign",
    "others": "Others",
    "show_name": "Show Name",
    "show_phone": "Show Phone",
    "show_address": "Show Address",
    "show_special_insturction": "Show Special Instruction ",
    "mask_phone": "Mask Phone",
    "show_from_name_tooltip": "Display location from (store) name on courier task report",
    "show_from_phone_tooltip": "Display location from (store)  phone on courier task report",
    "show_from_address_tooltip": "Display location from (store)  address on courier task report",
    "show_from_special_instruction_tooltip": "Display location from (store)  special instruction on courier task report",
    "show_from_mask_phone_tooltip": "Display location from (store)  phone on courier on-going task",
    "show_to_name_tooltip": "Display location to (customer) name on courier task report",
    "show_to_phone_tooltip": "Display location to  (customer) phone on courier task report",
    "show_to_address_tooltip": "Display location to  (customer) address on courier task report",
    "show_to_special_instruction_tooltip": "Display location to (customer) special instructio on courier task report",
    "show_to_mask_phone_tooltip": "Display location to (customer) phone on courier on-going task",
    "driver_check_in": "Driver Check in",
    "has_no_tasks": "Has no task",
    "driver_distance": "Driver Distance",
    "driver_has_shift": "Driver has Shift",
    "assign_statuses": "Auto Assign Statuses",
    "auto_assign_tooltip": "Auto assign task to a courier",
    "driver_check_in_tooltip": "Only assigning task to a courier that is check in",
    "has_no_tasks_tooltip": "Only assigning task to a courier that has no task",
    "driver_distance_tooltip": "Only assigning task to a courier that is within x km",
    "driver_has_shift_tooltip": "Only assigning task to a courier that has a shift",
    "assign_statuses_tooltip": "Only assigning task when task is updated to below status",
    "auto_assign_driver_distance": "Driver Distance",
    "time_slot": "Availabilities Time Slot",
    "time_slot_gap": "Time Slot Gap",
    "time_range_tooltip": "Availabilities time slot time range length (in mins)",
    "time_slot_gap_tooltip": "Gap between each availabilities time slot (in mins)",
    "third_party": "Third Party",
    "allowed_app": "Allowed Apps",
    "allowed_app_tooltip": "Apps allowed to modifty and access stores' information using third part (API) keys",
    "call_forward_valid_period": "Call Forward Valid Period",
    "call_forward_valid_period_tooltip": "Call Forward Valid Period",
    "require_availability": "Require Availability",
    "require_availability_tooltip": "Require Couriers to submit availabities"
  },
  "common_modals": {
    "organization": "Organization",
    "organization_name": "Organization Name",
    "organization_info": "Organization Info",
    "switch_organization": "Switch Organization",
    "store_info": "Store Info",
    "region": "Region",
    "order_info": "Order Info",
    "time_info": "Time Info",
    "add_task": "Add Task",
    "display_format": "Display Format",
    "payment_method": "Payment Method",
    "amount_to_collect": "Amount to Collect",
    "bonus": "Bonus",
    "amount_to_pay": "Amount to Pay",
    "stated_tips": "Stated Tips",
    "option": "Option",
    "desired_pickup_start": "Desired Pickup Start",
    "desired_pickup_length": "Desired Pickup Length",
    "desired_delivery_start": "Desired Delivery Start",
    "desired_delivery_lenght": "Desired Delivery Length",
    "expected_pickup_utc": "Expected pickup time",
    "expected_delivery_utc": "Expected delivery time",
    "desired_pickup_range": "Desired Pickup Range",
    "desired_delivery_range": "Desired Delivery Range",
    "expected_pickup_time": "Expected Pickup Time",
    "expected_delivery_time": "Expected Delivery Time",
    "hide_detail_before_accept": "Hide detail before accept",
    "shows_addresses_but_no_item_payment_amount_before_accept": "Shows addresses but no item payment amount before accept",
    "show_addresses_payment_acount_but_no_items": "Show addresses payment acount but no items",
    "show_all_info": "Show all info",
    "fee_rule_info": "Fee rule info",
    "collection_time_limit_required": "Collection time limit required",
    "search_tasks_with": "Search Tasks With",
    "task_filter": "Task Filter",
    "couriers_filter": "Couriers Filter",
    "created_range": "Created Range",
    "assigned_range": "Assigned Range",
    "delivered_range": "Delivered Range",
    "search_couriers_with": "Search Couriers With",
    "courier_name": "Courier Name",
    "max_location_age": "Max Location Age",
    "zones_filter": "Zones Filter",
    "user_info": "User Info",
    "courier": "Courier",
    "time_range": "Time Range",
    "time_zone": "Time Zone",
    "organ_store": "Organization Store",
    "store(optional)": "Store (Opt)",
    "user_profile": "User Profile",
    "working_info": "Working Info",
    "courier_report": "Courier Report",
    "transit_pay_from_driver_to_store": "Transit Pay (for the distance from driver to store)",
    "per_km_fee_to_store": "Per KM pay",
    "driver_compensate_for_waiting": "Driver Compensation for In Store Waiting",
    "collection_time_limit": "Payment Free Waiting Time Limit",
    "collection_fee_per_min": "Per Min Pay (when over the limit)",
    "transit_pay_from_store_to_customer": "Transit Pay (for the distance from store to customer)",
    "per_km_fee_to_customer": "Per KM Pay (when over the flat fee distance)",
    "default_fee_rule": "Default fee rule",
    "re-assign": "Re-assign",
    "assign_task": "Assign Task",
    "address_info": "Address Info",
    "items_info": "Items Info",
    "other_info": "Other Info",
    "duration": "Duration",
    "status_time_line": "Status Time Line",
    "distance": "Distance",
    "task": "Task",
    "task_details": "Task details",
    "stated_payment_method": "Stated payment method",
    "expected_time_info": "Expected Time Info",
    "pick_up": "Pick up",
    "delivery": "Delivery",
    "desired_delivered": "Desired Delivered",
    "deadline": "Deadline",
    "fit_shift": "Fit Shift",
    "has_shift": "Has Shift",
    "check_in": "Check in",
    "has_location": "Has Location",
    "no_shift_info": "No Shift Info",
    "open_task": "Open task",
  },
  "common_modal_errors": {
    "store_name_required": "Store name is required",
    "store_name_invalid": "Store name is invalid",
    "name_invalid": "Name is invalid",
    "postal_code_invalid": "Postal code is invalid",
    "postal_code_required": "Postal code is required",
    "order_id_invalid": "Order id is invalid",
    "order_id_required": "Order id is required",
    "payment_method_invalid": "Payment method is invalid",
    "payment_method_required": "Payment method is required",
    "display_format_required": "Display format is required",
    "desired_pickup_start_required": "Expected pickup start is required",
    "desired_pickup_length_required": "Expected pickup length is required",
    "desired_delivery_start_required": "Expected delivery start is required",
    "desired_delivery_lenght_required": "Expected delivery length is required",
    "phone_required": "Phone is required",
    "phone_invalid": "Phone is invalid",
  },
  "common_shifts": {
    "shifts": "Shifts",
    "open_shifts": "Open Shifts",
    "courier_shifts": "Courier Shifts",
    "shift_length": "Shift Length",
    "zone_id": "Zone",
    "zone": "Zone",
    "shift_info": "Shift Info",
    "start_time": "Start Time",
    "end_time": "End Time",
    "shift_type": "Shift Type",
    "status": "Status",
    "max_couriers": "Max Couriers",
    "bonus_pay": "Bonus Pay",
    "out_of_stock": "Out of stock",
    "regular": "Regular",
    "oncall": "Oncall",
    "overflow": "Overflow",
    "active": "Active",
    "cancelled": "Cancelled",
    "inactive": "Inactive",
    "closed": "Closed",
    "courier_shifts_filter": "Courier Shifts filter",
    "openShifts": "Open Shifts",
    "courierShifts": "Courier Shifts",
  },
  "common_price": {
    "total": "Total",
    "subtotal": "Subtotal",
    "discount": "Discount",
    "store_discount": "Store Discount",
    "coupon_discount": "Coupon Discount",
    "shipping_and_handling": "Shipping & Handling",
    "total_before_tax": "Total Before Tax",
    "tax": "Tax",
    "order_total": "Order Total",
    "gift_card_payment": "Gift card Payment",
    "points_payment": "Points Payment",
    "total_paid": "Total Paid",
    "total_due": "Total Due",
    "tips": "Tips",
    "delivery_fee": "Delivery Fee",
    "max_amount": "Max Amount",
    "min_amount": "Min Amount",
    "balance": "Balance",
    "amt": "Amount",
    "price": "Price",
    "item(s)": "Item(s)",
    "shopping": "Shopping",
    "billing_shipping": "Billing & Shipping",
    "done": "Done",
    "customer_info": "Customer Info",
    "delivery_info": "Delivery Info",
    "payment_info": "Payment Info",
    "other_payment_info": "Other Payment Info",
  },
  "common_†ime": {
    "date": "Date",
    "today": "Today",
    "yesterday": "Yesterday",
    "this_week": "This week",
    "last_week": "Last week",
    "this_month": "This Month",
    "last_month": "Last Month",
    "select_date": "Select date",
    "select_time": "Select time",
    "expiry_date": "Expiry date",
    "delivery_time": "Delivery Time",
    "pickup_time": "Pickup Time",
    "open_all_day": "OPEN ALL DAY",
    "closed_all_day": "CLOSED ALL DAY",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "mon": "MON",
    "tue": "TUE",
    "wed": "WED",
    "thu": "THU",
    "fri": "FRI",
    "sat": "SAT",
    "sun": "SUN",
    "open_247": "Open 24/7",
    "add_periods": "Add Periods",
    "expiration_utc": "Expiry Date",
    "updated_utc": "Updated Time",
    "created_utc": "Created Time",
    "last_updated_at": "Last Updated at"
  },
  "common_language": {
    "language": "Language",
    "en": "English",
    "zh": "简体中文",
    "zh-Hant": "繁體中文",
    "jp": "日本語",
  },
  "common_address": {
    "add_address": "Add address",
    "address": "Address",
    "street": "Street",
    "unit": "Unit",
    "buzzer": "Buzzer",
    "city": "City",
    "province": "Province",
    "country": "Country",
    "postal_code": "Postal code",
    "quick_map_search": "Quick Map Search",
    "map_search": "Map search",
    "shipping_address": "Shipping Address",
    "billing_address": "Billing Address",
    'set_as_default': "Set as default",
  },
  "common_error": {
    "unable_to_load_any_data": "Unable to load data",
    "unstable_network": "Slow or unstable network, please check your network connection",
    "logout_force_message": "Sorry, your account has been logged in from another device or has timed out. Please login again.",
    "incorrect_password": "Incorrect password",
    'incorrect_username_password': 'Incorrect username/password',
    'verification_code_expired': 'Verification code expired',
    'verifcation_code_request_overlimit': 'Verification code request overlimit',
    'incorrect_verification_code': 'Incorrect verification code',
    "login_failed": "Failed to login",
    "profile_update_success": "Update profile success",
    "email_update_success": "Update email success",
    "phone_update_success": "Update phone number success",
    "failed_fetch_gift_card_detail": "Failed to fetch gift card detail",
    "gift_card_transfer_success": "Tranfered gift card success",
    "gift_card_transfer_fail": "Failed to tranfer gift card",
    "invalid_request": "Invalid request",
    "record_not_found": "Record not found",
    "general_error": "Unexpected error occured, please try again later",
    "failed_fetch_points_detail": "Failed to fetch points details",
    "profile_update_failed": "Failed to update user profile",
    "email_update_failed": "Failed to update email",
    "phone_update_failed": "Failed to update phone number",
    "get_verification_code_success": "Verification code has been sent to your phone.",
    "verification_too_many_requests": "Verification code was requested too many times, please try again later",
    "phone_number_invalid": "Invalid phone number",
    "error": "Error",
    "unexpected_error": "An unexpected error has occurred, please try again later",
    "email_required": "Your email address is required",
    "name_required": "Name is required",
    "password_required": "Password is required",
    "street_required": "Street is required",
    "city_required": "City is required",
    "country_required": "Country code is required",
    "region_required": "Region is required",
    "postal_code_required": "Postal code is required",
    "one_more_fields_are_missing": "One or more fields are missing",
    "first_name_required": "First Name is required",
    "last_name_required": "Last Name is required",
    "phone_invalid": "Last Name is required",
    "first_name_invalid": "First Name must be at least 2 characters",
    "last_name_invalid": "Last Name must be at least 2 characters",
    "email_invalid": "Email address must be in the format 'someone@something.something'",
    "password_one_required": "Password is required",
    "password_two_required": "The confirm password is required",
    "password_one_invalid": "Must contain at least 1 lowercase and 1 uppercase alphabetical character, and at least 6 characters or longer",
    "password_two_invalid": "Your passwords do not match",
    "password_invalid": "Password is invalid",
    "email_existed": "The email entered has been taken.",
    "email_is_incorrect": "Cannot find user by the given username",
    "password_is_incorrect": "Password is not correct",
    "token_required": "Token is required",
    "organization_name_required": "Organization name is required",
    "token_invalid": "Invalid Token, please contact 778-379-7918 to get a valid token",
    "organization_name_invalid": "Organization name should be at least 5 characters or longer",
    "updated_zone_success": "Zone Information Updated",
    "created_task_success": "Task created",
    "created_open_shift_success": "Open shift created",
    "assigned_task_success": "Task assigned",
    "create_fee_rule_success": "Fee rule created",
    "update_fee_rule_success": "Fee rule updated",
    "delete_fee_rule_success": "Fee rule deleted",
    'profile_updated': 'Profile updated',
    "updated_task_success": "Task updated",
    "update_open_task_status_failed": "Failed to update open task status, please try again later",
    "updated_open_shift_success": "Open shift updated",
    "deleted_open_shift_success": "Open shift deleted",
    "created_store_success": "Store created",
    "updated_store_success": "Store updated",
    "deleted_courier_shift_success": "Courier shift deleted",
    "function_not_supported": "This function is currently not supported, come back later :)",
    "get_route_failure_message": "Directions request failed due to {status}",
    "assigned_task_warning": "Task is at '{status}' status, are you sure you want to re-assign this task?",
    "update_document_status_success": "Document status updated",
    "courier_info_updated": "Courier info updated",
    "x_is_required_create_a_store": "{value} is required to create a store",
    "delete_document_success": "Document deleted",
    "delete_store_success": "Store deleted",
    "updated_customer_success": "Customer updated",
    "created_customer_success": "Cutomer created",
    "delete_customer_success": "Cutomer deleted",
    "request_deleted": "Request deleted",
    "request_updated": "Request updated",
    "role_not_allowed": "Your role is not supported for this aciton",
    "are_you_sure_want_check_out_this_courier": "Check out this courier",
    "no_courier_found": "No Courier Found",
  },
  "common_acccount": {
    "my_account": "My account",
    "address_book": "Address book",
    "my_assets": "My assets",
    "log_in": "Log in",
    "logout": "Log out",
    "logout_confirm_message": "Are you sure you want to logout?",
    "login_with_text": "Login with text",
    "password": "Password",
    "remember_me": "Remember me",
    "login_with_account": "Login with account",
    "forgot_your_pw": "Forgot your password?",
    "become_carier": "Want to become a courier?",
    "sign_up_now": "Sign up now",
    "already_have_account": "Already have an account? ",
    "login_here": "Login Here",
    "password_one": "Password",
    "password_two": "Confirm Password",
    "sign_up": "Sign up",
    "log_in_mesage": "Sign In to your account",
    "register_now": "Register Now!",
    "register_promo_message": "If you're running or plan to run a delivery service business and looking for a system to manage the entire process, you can simply register your organization on this portal and get cloud based delivery platform to simplify your business operation and expedite your expansion. The whole system including call center portal, courier portal, courier mobile app, store portal etc.",
    "create_your_account": "Create your account",
    "create_organization": "Create Organization",
    "create_organaztion_mesage": "Create a new organization",
  },
  "common_country": {
    "canada": "Canada",
    "united_states": "United States",
    "china": "China",
    "south_korea": "South Korea"
  },
  "common_task": {
    "not_assigned": "Not Assigned",
    "rejected_by_courier": "Rejected by Courier",
    "assigned": "Assigned",
    "courier_accept_the_task": "Courier accepted the task",
    "ready_to_drive_to_store": "Ready to drive to store",
    "parked_at_the_store": "Parked at the store",
    "collected_item": "Collected item",
    "ready_drive_to_customer": "Ready to drive to customer",
    "parked_at_customer": "Parked at customer",
    "delivered_orded": "Delivered order"
  },
  "common_working_state": {
    "working_states": "Working States",
    "checked_in": "Checked In",
    "checked_out": "Checked out",
    "on_break": "On break"
  },
  "common_display_format": {
    "hide_all_before_accept": "Hide all before accept",
    "only_show_addresses": "Only show adddresses",
    "show_addresses_payment": "Show addresses and payment",
    "show_all_info": "Show all info",
  },
  "common_payment_method": {
    "paid": "Paid",
    "cash": "Cash",
    "pay_later_with_card": "Pay later with card",
  },
  "common_courier_status": {
    "approved": "Approved",
    "pending": "Pending",
    "rejected": "Rejected",
    "inreview": "Inreview",
    "applying": "Applying",
  },
  "common_role": {
    "super_user": "Super User",
    "supervisor": "Supervisor",
    "manager": "Manager",
    "agent": "Agent"
  },
  "common_relationship_to_store": {
    "relationship_to_store": "Relationship to Store",
    "owner": "Owner",
    "general_manager": "Genral Manager",
    "onsite_manager": "Onsite Manager",
    "accountant": "Accountant",
    "marketer": "Marketer",
    "chef": "Chef",
    "restaurant_staff": "Restaurant Staff",
  },
  "common_documents": {
    "profile_photo": "Profile Photo",
    "driver_license": "Driver License",
    "vehicle_insurance": "Vehicle Insurance",
    "vehicle_registration": "Vehicle Registration",
    "proof_of_work_eligibility": "Proof of Work Eligibility",
    "business_license": "Business License",
    "incorporation_certificate": "Incorporation Certificate",
    "store_owner_id": "Store Owner Id",
    "store_image": "Store Image",
    "void_check": "Void Check"
  },
  "common_delivery_options": {
    "delivery_option": "Delivery Option",
    "pick_up_outside": "Pick up outside",
    "deliver_to_door": "Deliver to door"
  },
  "common_delivery_label": {
    "school": "School",
    "office": "Office",
    "home": "Home"
  },
  "common_item_option": {
    'document': "Document",
    'certificates': "Certificates",
    'food': "Food",
    'cake': "Cake",
    'grocerry': "Grocerry",
    'cell_phone': "Cell phone",
    'computer': "Computer",
    'flower': "Flower",
    'funiture': "Funiture",
  },
  "common_business_type": {
    "restaurant": "Restaurant",
    "grocery": "Grocery",
    "fashion": "Fashion",
    "jewelry": "Jewelry",
    "appliance": "Appliance",
    "decoration": "Decoration",
    "furniture": "Furniture"
  },
  "common_restaurant_type": {
    "restaurant_type": "Restaurant Type",
    "African: Ethiopian": "African: Ethiopian",
    "African: Other": "African: Other",
    "Alcohol": "Alcohol",
    "American": "American",
    "Asian Fusion": "Asian Fusion",
    "Asian: Other": "Asian: Other",
    "BBQ": "BBQ",
    "Bakery": "Bakery",
    "Bar / Pub Food": "Bar / Pub Food",
    "Breakfast &amp;Brunch": "Breakfast &amp;Brunch",
    "Bubble Tea": "Bubble Tea",
    "Burgers": "Burgers",
    "Burmese": "Burmese",
    "Cajun / Creole": "Cajun / Creole",
    "Caribbean": "Caribbean",
    "Chicken": "Chicken",
    "Chinese: Cantonese": "Chinese: Cantonese",
    "Chinese: Hot Pot": "Chinese: Hot Pot",
    "Chinese: Noodles & Dumplings": "Chinese: Noodles & Dumplings",
    "Chinese: Other": "Chinese: Other",
    "Chinese: Sichuan": "Chinese: Sichuan",
    "Chinese: Taiwanese": "Chinese: Taiwanese",
    "Coffee & Tea": "Coffee & Tea",
    "Comfort Food": "Comfort Food",
    "Dessert: Other": "Dessert: Other",
    "European: Other": "European: Other",
    "Fish and Chips": "Fish and Chips",
    "French": "French",
    "Georgian": "Georgian",
    "German": "German",
    "Halal": "Halal",
    "Ice Cream & Frozen Yogurt": "Ice Cream & Frozen Yogurt",
    "Indian": "Indian",
    "Indonesian": "Indonesian",
    "Italian": "Italian",
    "Japanese: Other": "Japanese: Other",
    "Japanese: Ramen": "Japanese: Ramen",
    "Japanese: Sushi": "Japanese: Sushi",
    "Juice & Smoothies": "Juice & Smoothies",
    "Korean": "Korean",
    "Kosher": "Kosher",
    "Latin American: Other": "Latin American: Other",
    "Malaysian": "Malaysian",
    "Mediterranean": "Mediterranean",
    "Mexican": "Mexican",
    "Middle Eastern": "Middle Eastern",
    "Modern Australian": "Modern Australian",
    "Other": "Other",
    "Pizza": "Pizza",
    "Russian": "Russian",
    "Salad / Sandwiches": "Salad / Sandwiches",
    "Seafood": "Seafood",
    "Snacks": "Snacks",
    "Soul Food": "Soul Food",
    "Southern": "Southern",
    "Spanish": "Spanish",
    "Steakhouse": "Steakhouse",
    "Thai": "Thai",
    "Vegetarian / Vegan": "Vegetarian / Vegan",
    "Vietnamese": "Vietnamese",
    "Wings": "Wings"
  },
  "landing-page": {
    "welcome_to_courier_portal": "Welcome to the Courier Portal",
    "download_apps_message": "Download the latest version of the Courier application for the iPhone or Android smart phone. You must be on your phone to download the application"
  },
  "signup-page": {
    "delivery_with_goopter": "Deliver with Goopter",
    "delivery_with_goopter_message": "In just a few easy steps, you’ll be cruising towards making extra money. It’s a flexible opportunity that you can customize to fit your lifestyle.",
    "choose_your_schedule": "Choose Your Schedule",
    "choose_messages": "You are in control of your own schedule and can adjust your weekly availability based on what works for you.",
    "get_paid_messages": "At the end of each week, your earnings and tips will be directly deposited into your account every week.",
    "get_paid_weekly": "Get Paid Weekly",
  }
}