export default {
  "common": {
    " ": " ",
    "yes": "是",
    "no": "否",
    "confirm": "确认",
    "assign": "分配",
    "delete": "删除",
    "ok": "确认",
    "close": "关闭",
    "filter": "筛选",
    "product": "产品",
    "store": "商店",
    "loading": "载入中...",
    "setting": "设置",
    "back": "后退",
    "dashboard": "控制面板",
    "zones": "区域",
    "stores": "商店",
    "couriers": "配送人员",
    "tasks": "任务",
    "orders": "订单",
    "notification": "消息",
    "warning": "警告",
    "submit": "提交",
    "cancel": "取消",
    "comment": "备注",
    "tel": "电话",
    "phone_number": "电话号码",
    "not_set": "未设置",
    "name": "姓名",
    "email": "电邮",
    "customer": "客户",
    "admin": "管理",
    "current": "当前",
    "newest": "最新",
    "Skipped": "Skipped",
    "clear_all": "清除所有",
    "all": "全部",
    "save": "保存",
    "disabled": "禁用",
    "margin": "页边距",
    "top": "上",
    "bottom": "下",
    "left": "左",
    "right": "右",
    "general": "通用",
    "general_settings": "通用设置",
    "first_name": "名",
    "last_name": "姓",
    "status": "状态",
    "new": "新",
    "reload": "刷新",
    "selected": "已选",
    "items": "项",
    "clear_fliter": "清除篩選條件",
    "search": "搜索",
    "enter_password": "请输入密码",
    "unlock": "解锁",
    "qty": "数量",
    "gift_cards": "礼品卡",
    "view_all": "查看全部",
    "profile": "个人资料",
    "nick_name": "昵称",
    "verification_code": "验证码",
    "get_verification_code": "获取验证码",
    "edit": "编辑",
    "action": "行动",
    "send": "发送",
    "receiver": "收货人",
    "email_phone": "电子邮件/电话",
    "change": "改变",
    "description": "描述",
    "remove": "删除",
    "apply": "应用",
    'complete_oreder': "完成订单",
    "category": "类别",
    "expired": "已过期",
    "optional": "可选",
    "about": "关于",
    "highlights": "亮点",
    "customer_reviews": "客户评论",
    "relevant_reviews": "相关评论",
    "ratings": "评级",
    "reviews": "评论",
    "buy": "购买",
    "quantity": "数量",
    "out_of_stock": "缺货",
    "first": "第一",
    "second": "第二",
    "previous": "上一步",
    "next": "下一步",
    "get_started": "开始",
    "token": "令牌",
    "home": "首页",
    "add": "添加",
    "are_you_sure": "你确定吗?",
    "feerules": "收费规则",
    "false": "False",
    "true": "True",
    "no_new_noti": "没有新提醒",
    "ready": "准备",
    "not_available": "不可用",
    "role": "Role",
    "customers": "Customers",
    "staffs": "Staffs",
    "contact_name": "Contact Name",
    "availabitlies": "Availabitlies",
    "subscribed_couriers": "Subscribed Couriers",
    "search_stores_with": "Search Store With...",
    "fee_rules": "Fee Rules",
    "sort_by": "Sort By",
    "documents": "Documents",
    "business_number": "Business Number",
    "value_added_tax_account_number": "Value Added Tax Account Number",
    "vat": "Value Added Tax Account Number",
    "business_start_dt": "Business Start Date",
    "special_instruction": "Special Instruction",
    "shared_customer": "Share Customer",
    "share_address_book": "Share Address Book",
    "third_party_access": "Third Party Access",
    "allow_third_party_access": "Allow Third Party Access",
    "contact_first_name": "Contact First Name",
    "contact_last_name": "Contact Last Name",
    "label": "Label",
    "business_building_name": "Business Building Name",
    "customer(optional)": "Customer(Opt)",
    "search_customers_with": "Search Customer With...",
    "customer_name/phone": "Customer Name/Phone",
    "ongoing": "Ongoing",
    "business_name": "Business Name",
    "auto_save": "Auto Save",
    "add_an_item": "Add an Item",
    "add_an_option": "Add an Option",
    "delivered_items": "Deliver Items",
    "staff": "Staff",
  },
  "common_column_titles": {
    "name": "姓名",
    "contact": "联系人",
    "phone": "手机号码",
    "action": "操作",
    "store_name": "商店名称",
    "address": "地址",
    "fee_rule": "付费规则",
    "order_id": "订单号",
    "store": "店家",
    "pickup_range": "取货时间",
    "delivery_range": "送达时间",
    "from": "发货人",
    "to": "收货人",
    "status": "配送状态",
    "confirmed": "已确认",
    "info": "信息",
    "working_state": "工作状态",
    "active_zones": "活跃区域",
    "subscribed_zones": "订阅的区域",
    "hours/week": "小时/周",
    "names": "名称",
    "time_limit": "时间限制",
    "dollar_min": "$/分钟",
    "dollar/km_store": "$/km (商店)",
    "dollar/km_customer": "$/km (顾客)",
    "can_override": "允许用户修改配送费",
    "contact_info": "联系方式",
    "office_info": "办公室信息",
    "zone_name": "区域名称",
    "base_distance": "平价配送距离",
    "base_fee": "起步价",
    "active_stores": "已批准的商家",
    "pending_stores": "等待提交中的商家",
    "pendingStores": "等待提交中的商家",
    "pending_store": "等待提交中的商家",
    "pending_store(other)": "等待提交中的商家（其他）",
    "website": "网站",
    "business_type": "生意类型",
    "number_of_locations": "分店数量",
    "report": "报表",
    "last_seen": "最近在线",
    "working_state_desc": "快递员在工作场所的出勤状况。",
    "active_zones_desc": "配送员当前的工作区域",
    "subscribed_zones_desc": "配送员选择的工作区域。",
    "collection_fee_per_min_desc": "超过免费等待时间的每分钟等候费用(给配送员)",
    "base_distance_desc": "公司付给配送员的平价配送距离",
    "per_km_fee_to_store_desc": "从配送员到商家的每公里的费用",
    "per_km_fee_to_customer_desc": "支付给配送员的超过平价配送距离后的每公里费用",
    "collection_time_limit_desc": "到商家提货时候的免费等待时间",
    "base_fee_desc": "支付给配送员的平价配送费用",
    "can_override_desc": "是否允许商家修改配送费用",
    "share_address_book_tooltip": "Allow Organization to access store customer address book",
    "allow_third_party_access_tooltip": "Allow Third Party (API Key) access and edit store information",
    "generate_next_order_id": "Generate next order Id",
    "delivery_fee_descript": "Delivery Fee is calcated based on store fee rule if it is not set",
    "calulate_estimated_delivery_Fee": "Calculate Esistmated Delivery Fee",
    "store_was_not_entered_or_not_recognized": "Please enter location from info",
    "fee_rule_was_not_assigned_to_the_selected_store_or_fee_rule_not_recognized": "Fee rule is not assigned to the selected store or fee rule is not recognized",
    "please_enter_destination_info": "Please enter destination info",
  },
  "common_setting": {
    "task_display": "Task Display",
    "auto_assign": "Auto Assign",
    "others": "Others",
    "show_name": "Show Name",
    "show_phone": "Show Phone",
    "show_address": "Show Address",
    "show_special_insturction": "Show Special Instruction ",
    "mask_phone": "Mask Phone",
    "show_from_name_tooltip": "Display location from (store) name on courier task report",
    "show_from_phone_tooltip": "Display location from (store)  phone on courier task report",
    "show_from_address_tooltip": "Display location from (store)  address on courier task report",
    "show_from_special_instruction_tooltip": "Display location from (store)  special instruction on courier task report",
    "show_from_mask_phone_tooltip": "Display location from (store)  phone on courier on-going task",
    "show_to_name_tooltip": "Display location to (customer) name on courier task report",
    "show_to_phone_tooltip": "Display location to  (customer) phone on courier task report",
    "show_to_address_tooltip": "Display location to  (customer) address on courier task report",
    "show_to_special_instruction_tooltip": "Display location to (customer) special instructio on courier task report",
    "show_to_mask_phone_tooltip": "Display location to (customer) phone on courier on-going task",
    "driver_check_in": "Driver Check in",
    "has_no_tasks": "Has no task",
    "driver_distance": "Driver Distance",
    "driver_has_shift": "Driver has Shift",
    "assign_statuses": "Auto Assign Statuses",
    "auto_assign_tooltip": "Auto assign task to a courier",
    "driver_check_in_tooltip": "Only assigning task to a courier that is check in",
    "has_no_tasks_tooltip": "Only assigning task to a courier that has no task",
    "driver_distance_tooltip": "Only assigning task to a courier that is within x km",
    "driver_has_shift_tooltip": "Only assigning task to a courier that has a shift",
    "assign_statuses_tooltip": "Only assigning task when task is updated to below status",
    "auto_assign_driver_distance": "Driver Distance",
    "time_slot": "Availabilities Time Slot",
    "time_slot_gap": "Time Slot Gap",
    "time_range_tooltip": "Availabilities time slot time range length (in mins)",
    "time_slot_gap_tooltip": "Gap between each availabilities time slot (in mins)",
    "third_party": "Third Party",
    "allowed_app": "Allowed Apps",
    "allowed_app_tooltip": "Apps allowed to modifty and access stores' information using third part (API) keys",
    "call_forward_valid_period": "Call Forward Valid Period",
    "call_forward_valid_period_tooltip": "Call Forward Valid Period",
    "require_availability": "Require Availability",
    "require_availability_tooltip": "Require Couriers to submit availabities",
  },
  "common_modals": {
    "organization": "组织",
    "organization_name": "组织名称",
    "organization_info": "组织信息",
    "switch_organization": "更换组织",
    "store_info": "商店信息",
    "region": "地区",
    "order_info": "配送信息",
    "time_info": "配送时间",
    "add_task": "添加任务",
    "display_format": "显示格式",
    "payment_method": "支付方式",
    "amount_to_collect": "收取金额",
    "bonus": "奖金",
    "amount_to_pay": "支付商家金额",
    "stated_tips": "声明小费金额",
    "option": "选项",
    "desired_pickup_start": "要求取货时间",
    "desired_pickup_length": "要求取货时间跨度",
    "desired_delivery_start": "要求配送时间",
    "desired_delivery_lenght": "要求配送时间跨度",
    "expected_pickup_utc": "预计取货时间",
    "expected_delivery_utc": "预计配送时间",
    "desired_pickup_range": "要求取货时间",
    "desired_delivery_range": "要求配送时间",
    "expected_pickup_time": "预计取货时间",
    "expected_delivery_time": "预计配送时间",
    "hide_detail_before_accept": "接受前隐藏配送细节",
    "shows_addresses_but_no_item_payment_amount_before_accept": "在接受之前显示地址但不显示产品信息及配送费",
    "show_addresses_payment_acount_but_no_items": "显示地址及配送费，但不显示产品信息",
    "show_all_info": "显示所有信息",
    "fee_rule_info": "收费规则",
    "collection_time_limit_required": "请输入提货时间限制",
    "search_tasks_with": "搜索任务",
    "task_filter": "任务筛选",
    "couriers_filter": "筛选配送员",
    "created_range": "任务创建时间范围",
    "assigned_range": "任务分配时间范围",
    "delivered_range": "配送距离",
    "search_couriers_with": "搜索配送员",
    "courier_name": "配送员名",
    "max_location_age": "位置的最早时间",
    "zones_filter": "区域筛选",
    "user_info": "用户信息",
    "courier": "配送人员",
    "time_range": "时间范围",
    "time_zone": "时区",
    "organ_store": "组织及商家",
    "store(optional)": "商家 (可选的)",
    "user_profile": "用户资料",
    "working_info": "工作状态信息",
    "courier_report": "配送员报表",
    "transit_pay_from_driver_to_store": "配送费 (按司机到商家之间的距离来算)",
    "per_km_fee_to_store": "司机到商家每公里交通补贴",
    "driver_compensate_for_waiting": "配送员在商家等待的补偿费用",
    "collection_time_limit": "免费的等待时间限制",
    "collection_fee_per_min": "超过免费等待时间后的每分钟额外费用",
    "transit_pay_from_store_to_customer": "配送费 (按商家到客戶间的距离来算)",
    "per_km_fee_to_customer": "超过平价配送费用后每公里的额外费用",
    "default_fee_rule": "Default fee rule",
    "re-assign": "重新分配",
    "assign_task": "分配任务",
    "address_info": "地址信息",
    "items_info": "商品信息",
    "other_info": "Other Info",
    "duration": "时长",
    "status_time_line": "时间状态线",
    "distance": "距离",
    "task": "任务",
    "task_details": "任务详情",
    "stated_payment_method": "预计付款方式",
    "expected_time_info": "期待时间信息",
    "pick_up": "取货",
    "delivery": "配送",
    "desired_delivered": "期待送达",
    "deadline": "截止日期",
    "fit_shift": "Fit Shift",
    "has_shift": "Has Shift",
    "check_in": "Check in",
    "has_location": "Has Location",
    "no_shift_info": "No Shift Info",
    "open_task": "Open task",
  },
  "common_modal_errors": {
    "store_name_required": "请输入店名",
    "store_name_invalid": "无效的店名",
    "name_invalid": "无效的店名",
    "postal_code_invalid": "无效的邮编",
    "postal_code_required": "请输入邮编",
    "order_id_invalid": "无效的订单号",
    "order_id_required": "请输入订单号",
    "payment_method_invalid": "无效的付款方式",
    "payment_method_required": "请输入付款方法",
    "display_format_required": "请输入显示格式",
    "desired_pickup_start_required": "请输入提货时间",
    "desired_pickup_length_required": "请输入提货时间长度",
    "desired_delivery_start_required": "请输入发货时间",
    "desired_delivery_lenght_required": "请输入发货时间长度",
    "phone_required": "请输入手机号",
    "phone_invalid": "无效的手机号",
  },
  "common_shifts": {
    "shifts": "Shifts",
    "open_shifts": "Open Shifts",
    "courier_shifts": "Courier Shifts",
    "shift_length": "工时",
    "zone_id": "区域",
    "zone": "区域",
    "shift_info": "班次讯息",
    "start_time": "起始时间",
    "end_time": "结束时间",
    "shift_type": "班次类型",
    "status": "状态",
    "max_couriers": "配送人员上限",
    "bonus_pay": "提成",
    "out_of_stock": "售罄",
    "regular": "常规",
    "oncall": "随传随到",
    "overflow": "临时轮班",
    "active": "进行中",
    "cancelled": "已取消",
    "inactive": "停止",
    "closed": "已关闭",
    "courier_shifts_filter": "配送人员的排班过滤器",
    "openShifts": "公开排班",
    "courierShifts": "配送人员的排班",
  },
  "common_price": {
    "total": "Total",
    "subtotal": "商品總價",
    "discount": "折扣",
    "store_discount": "商家折扣",
    "coupon_discount": "打折券",
    "shipping_and_handling": "配送费",
    "total_before_tax": "税前金额",
    "tax": "税",
    "order_total": "总价",
    "gift_card_payment": "礼品卡支付",
    "points_payment": "积分支付",
    "total_paid": "已付款",
    "total_due": "应付款",
    "tips": "小费",
    "delivery_fee": "配送费",
    "max_amount": "最高金额",
    "min_amount": "最低金额",
    "balance": "余额",
    "amt": "总额",
    "price": "价格",
    "item(s)": "物件",
    "shopping": "购物",
    "billing_shipping": "结算和运输",
    "done": "完成",
    "customer_info": "客户信息",
    "delivery_info": "运输信息",
    "payment_info": "付款信息",
    "other_payment_info": "其他付款信息",
  },
  "common_†ime": {
    "date": "日期",
    "today": "今天",
    "yesterday": "昨天",
    "this_week": "本星期",
    "last_week": "上个星期",
    "this_month": "這個月",
    "last_month": "上個月",
    "select_date": "选择日期",
    "select_time": "选择时间",
    "expiry_date": "过期日",
    "delivery_time": "配送时间",
    "pickup_time": "取货时间",
    "open_all_day": "全天营业",
    "closed_all_day": "全天歇业",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "mon": "MON",
    "tue": "TUE",
    "wed": "WED",
    "thu": "THU",
    "fri": "FRI",
    "sat": "SAT",
    "sun": "SUN",
    "open_247": "Open 24/7",
    "add_periods": "Add Periods",
    "expiration_utc": "Expiry Date",
    "updated_utc": "Updated Time",
    "created_utc": "Created Time",
    "last_updated_at": "Last Updated at",
  },
  "common_language": {
    "language": "语言",
    "en": "English",
    "zh": "简体中文",
    "zh-Hant": "繁體中文",
    "jp": "日本語",
  },
  "common_address": {
    "add_address": "添加地址",
    "address": "地址",
    "street": "街道",
    "unit": "单元",
    "buzzer": "门铃",
    "city": "城市",
    "province": "省份",
    "country": "国家",
    "postal_code": "邮编",
    "quick_map_search": "快速地图搜索",
    "map_search": "地图搜索",
    "shipping_address": "配送地址",
    "billing_address": "账单地址",
    'set_as_default': "设为默认",
  },
  "common_error": {
    "unable_to_load_any_data": "无法加载数据",
    "unstable_network": "网络速度较慢或不稳定，请检查您的网络连接",
    "logout_force_message": "抱歉，您的帐户已从其他设备登录或超时，请重新登录。",
    "incorrect_password": "密码错误",
    'incorrect_username_password': '用户名/密码不正确",
    'verification_code_expired': '验证码已过期",
    'verifcation_code_request_overlimit': '验证码请求超限",
    'incorrect_verification_code': '验证码不正确",
    "login_failed": "登录失败",
    "profile_update_success": "更新个人资料成功",
    "email_update_success": "更新电子邮件成功",
    "phone_update_success": "更新电话号码成功",
    "failed_fetch_gift_card_detail": "无法获取礼品卡详细信息",
    "gift_card_transfer_success": "礼品卡转让成功",
    "gift_card_transfer_fail": "无法转让礼品卡",
    "invalid_request": "无效请求",
    "record_not_found": "未找到记录",
    "general_error": "发生意外错误，请稍后再试",
    "failed_fetch_points_detail": "无法获取积分详细信息",
    "profile_update_failed": "更新用户个人资料失败",
    "email_update_failed": "更新电子邮件失败",
    "phone_update_failed": "更新电话号码失败",
    "get_verification_code_success": "验证码已发送到您的手机",
    "verification_too_many_requests": "验证码已被请求过多次，请稍后再试",
    "phone_number_invalid": "无效的手机号",
    "error": "错误",
    "unexpected_error": "发生意外错误，请稍後再试",
    "email_required": "请输入您的电子邮件",
    "name_required": "请输入店名",
    "password_required": "请输入您的密码",
    "street_required": "请输入街道",
    "city_required": "请输入城市",
    "country_required": "请输入国家/地区代码",
    "region_required": "请输入地区",
    "postal_code_required": "请输入邮政编码",
    "one_more_fields_are_missing": "一个或以上的输入框未填",
    "first_name_required": "名字是必需的",
    "last_name_required": "姓氏是必需的",
    "phone_invalid": "Last Name is required",
    "first_name_invalid": "名字必须至少为2个字符",
    "last_name_invalid": "姓氏必须至少为2个字符",
    "email_invalid": "电子邮件地址的格式必须为 'someone@something.something'",
    "password_one_required": "需要密码",
    "password_two_required": "需要确认密码",
    "password_one_invalid": "必须包含至少1个小写字母和1个大写字母字符，且至少包含6个字符或更长",
    "password_two_invalid": "您的密码不匹配",
    "password_invalid": "密码无效",
    "email_existed": "该电子邮件已被占用.",
    "email_is_incorrect": "用户名不存在",
    "password_is_incorrect": "密码不正确",
    "token_required": "需要令牌",
    "organization_name_required": "请输入组织名称",
    "token_invalid": "令牌无效, 请联系778-379-7918获取有效令牌",
    "organization_name_invalid": "组织名称必须为5个字符或以上",
    "updated_zone_success": "已更新区域任务",
    "created_task_success": "已建立任务",
    "created_open_shift_success": "已建立公开班次",
    "assigned_task_success": "已经分配任务",
    "create_fee_rule_success": "已建立付费规则",
    "update_fee_rule_success": "已更新付费规则",
    "delete_fee_rule_success": "已删除付费规则",
    'profile_updated': '已更新用户档案",
    "updated_task_success": "Task updated",
    "update_open_task_status_failed": "Failed to update open task status, please try again later",
    "updated_open_shift_success": "Open shift updated",
    "deleted_open_shift_success": "已删除公开排班",
    "created_store_success": "已创建商家",
    "updated_store_success": "已更新商家",
    "deleted_courier_shift_success": "已删除配送人员的排班",
    "function_not_supported": "此功能目前不支持，请稍后回来:)",
    "get_route_failure_message": "由于{status}状态，方向请求失败",
    "assigned_task_warning": "任务处于'{status}'状态, 您确定您要重新分配此任务吗？",
    "update_document_status_success": "已更新文件状态",
    "courier_info_updated": "已更新配送人员信息",
    "x_is_required_create_a_store": "需要{value}来创建商家",
    "delete_document_success": "已删除文件",
    "delete_store_success": "已删除商家",
    "updated_customer_success": "Customer updated",
    "created_customer_success": "Cutomer created",
    "delete_customer_success": "Cutomer deleted",
    "request_deleted": "Request deleted",
    "request_updated": "Request updated",
    "role_not_allowed": "Your role is not supported for this aciton",
    "are_you_sure_want_check_out_this_courier": "Check out this courier",
    "no_courier_found": "No Courier Found",
  },
  "common_acccount": {
    "my_account": "我的帐户",
    "address_book": "地址簿",
    "my_assets": "我的资产",
    "log_in": "登录",
    "logout": "登出",
    "logout_confirm_message": "您确认要签退吗?",
    "login_with_text": "手机短信登陆",
    "password": "密码",
    "remember_me": "记住我",
    "login_with_account": "账户登陆",
    "forgot_your_pw": "忘记密码？",
    "become_carier": "想成为一名快递员？",
    "sign_up_now": "立即注册",
    "already_have_account": "已经有账号？ ",
    "login_here": "这里登录",
    "password_one": "密码",
    "password_two": "确认密码",
    "sign_up": "注册",
    "log_in_mesage": "登入你的账户",
    "register_now": "请注册",
    "register_promo_message": "如果您正在或计划开展配送业务，需要一个系统来管理整个业务流程，您只需在此注册您的组织，这将大大简化您的业务操作流程，让您可以快速拓展。 整个系统是基于云计算计算，包括呼叫中心，派送员网站系统，配送员移动APP，商家网站系统，商家App等。",
    "create_your_account": "建立你的账户",
    "create_organization": "建立你的组织",
    "create_organaztion_mesage": "建立组织信息",
  },
  "common_country": {
    "canada": "加拿大",
    "united_states": "美国",
    "china": "中国",
    "south_korea": "韩国",
  },
  "common_task": {
    "not_assigned": "没有被分配",
    "rejected_by_courier": "已被配送人员拒绝",
    "assigned": "已被分配",
    "courier_accept_the_task": "配送人员已接受了任务",
    "ready_to_drive_to_store": "准备开往商店",
    "parked_at_the_store": "已停靠在商店",
    "collected_item": "已经收取货物",
    "ready_drive_to_customer": "准备开往顾客",
    "parked_at_customer": "已停靠在顾客",
    "delivered_orded": "已发货",
  },
  "common_working_state": {
    "working_states": "Working States",
    "checked_in": "Checked In",
    "checked_out": "Checked out",
    "on_break": "On break",
  },
  "common_display_format": {
    "hide_all_before_accept": "Hide all before accept",
    "only_show_addresses": "Only show adddresses",
    "show_addresses_payment": "Show addresses and payment",
    "show_all_info": "Show all info",
  },
  "common_payment_method": {
    "paid": "Paid",
    "cash": "Cash",
    "pay_later_with_card": "Pay later with card",
  },
  "common_courier_status": {
    "approved": "Approved",
    "pending": "Pending",
    "rejected": "Rejected",
    "inreview": "Inreview",
    "applying": "Applying",
  },
  "common_role": {
    "super_user": "Super User",
    "supervisor": "Supervisor",
    "manager": "Manager",
    "agent": "Agent",
  },
  "common_relationship_to_store": {
    "relationship_to_store": "Relationship to Store",
    "owner": "Owner",
    "general_manager": "Genral Manager",
    "onsite_manager": "Onsite Manager",
    "accountant": "Accountant",
    "marketer": "Marketer",
    "chef": "Chef",
    "restaurant_staff": "Restaurant Staff",
  },
  "common_documents": {
    "profile_photo": "Profile Photo",
    "driver_license": "Driver License",
    "vehicle_insurance": "Vehicle Insurance",
    "vehicle_registration": "Vehicle Registration",
    "proof_of_work_eligibility": "Proof of Work Eligibility",
    "business_license": "Business License",
    "incorporation_certificate": "Incorporation Certificate",
    "store_owner_id": "Store Owner Id",
    "store_image": "Store Image",
    "void_check": "Void Check",
  },
  "common_delivery_options": {
    "delivery_option": "Delivery Option",
    "pick_up_outside": "Pick up outside",
    "deliver_to_door": "Deliver to door",
  },
  "common_delivery_label": {
    "school": "School",
    "office": "Office",
    "home": "Home",
  },
  "common_item_option": {
    'document': "Document",
    'certificates': "Certificates",
    'food': "Food",
    'cake': "Cake",
    'grocerry': "Grocerry",
    'cell_phone': "Cell phone",
    'computer': "Computer",
    'flower': "Flower",
    'funiture': "Funiture",
  },
  "common_business_type": {
    "restaurant": "Restaurant",
    "grocery": "Grocery",
    "fashion": "Fashion",
    "jewelry": "Jewelry",
    "appliance": "Appliance",
    "decoration": "Decoration",
    "furniture": "Furniture",
  },
  "common_restaurant_type": {
    "restaurant_type": "Restaurant Type",
    "African: Ethiopian": "非洲风味: 埃塞俄比亚菜式",
    "African: Other": "非洲风味: 其他",
    "Alcohol": "酒精",
    "American": "北美风味",
    "Asian Fusion": "亚洲美食",
    "Asian: Other": "亚洲风味: 其他",
    "BBQ": "烧烤",
    "Bakery": "烘培",
    "Bar / Pub Food": "酒吧/酒馆食物",
    "Breakfast &amp;Brunch": "早餐&amp;早午餐",
    "Bubble Tea": "泡沫奶茶",
    "Burgers": "汉堡",
    "Burmese": "缅甸风味",
    "Cajun / Creole": "卡津/克里奥尔菜式",
    "Caribbean": "加勒比风",
    "Chicken": "鸡肉",
    "Chinese: Cantonese": "中式: 粤菜",
    "Chinese: Hot Pot": "中式: 火锅",
    "Chinese: Noodles & Dumplings": "Chinese: Noodles & Dumplings",
    "Chinese: Other": "中式: 其他",
    "Chinese: Sichuan": "中式: 川菜",
    "Chinese: Taiwanese": "中式: 台式",
    "Coffee & Tea": "咖啡和茶",
    "Comfort Food": "舒心美食",
    "Dessert: Other": "点心: 其他",
    "European: Other": "欧式: 其他",
    "Fish and Chips": "鱼和薯片",
    "French": "法式",
    "Georgian": "喬治亞菜式",
    "German": "德式",
    "Halal": "清真",
    "Ice Cream & Frozen Yogurt": "冰淇淋和冰冻酸奶",
    "Indian": "印度",
    "Indonesian": "印尼餐",
    "Italian": "意式",
    "Japanese: Other": "日式: 其他",
    "Japanese: Ramen": "日式: 拉面",
    "Japanese: Sushi": "日式: 寿司",
    "Juice & Smoothies": "果汁和冰沙",
    "Korean": "韩式",
    "Kosher": "符合犹太教规的菜式",
    "Latin American: Other": "南美风: 其他",
    "Malaysian": "马来西亚菜",
    "Mediterranean": "地中海风",
    "Mexican": "墨西哥风",
    "Middle Eastern": "中东风味",
    "Modern Australian": "现代澳大利亚风",
    "Other": "其他",
    "Pizza": "披萨",
    "Russian": "俄罗斯菜式",
    "Salad / Sandwiches": "沙拉/三明治",
    "Seafood": "海鲜",
    "Snacks": "零嘴",
    "Soul Food": "美国非裔传统菜",
    "Southern": "美国南部风味",
    "Spanish": "西班牙菜式",
    "Steakhouse": "牛排店",
    "Thai": "泰式",
    "Vegetarian / Vegan": "素食/全素食者",
    "Vietnamese": "越式",
    "Wings": "鸡翅",
  },
  "landing-page": {
    "welcome_to_courier_portal": "欢迎来到快递门户网站",
    "download_apps_message": "下载适用于iPhone或Android智能手机的最新版配送应用程序。您必须在手机上才能下载该应用程序",
  },
  "signup-page": {
    "delivery_with_goopter": "够淘递送",
    "delivery_with_goopter_message": "只需几个简单的步骤，您就可以获得额外收入。这是一个灵活的机会，您可以自定义以适应您的生活方式。",
    "choose_your_schedule": "选择你的日程表",
    "choose_messages": "您可以掌控自己的日程安排，并可以根据适合您的方式调整每周工时。 ",
    "get_paid_messages": "在每周结束时，您的收入和小费将每周直接存入您的帐户。",
    "get_paid_weekly": "每周收入",
  }
}